apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users  
    spec:
      containers:
        - name: users
          image: dhrvsharma/kub-demo-users:v4
          env:
          # this is how containers of same pods communicate to each other 
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: dhrvsharma/auth-api:v1